### IMPORTING LIBRARIES

In [7]:
import pandas as pd
import numpy as np

### IMPORTING THE DATASET

In [8]:
audible_dataset=pd.read_csv(r'DATASETS\audible_uncleaned.csv')

## SUMMARY OF THE DATA
### THIS CONTAINS IMPORTANT DATA OF AUDIOBOOKS RELEASED FROM 1998 TO 2025
IT CONTAINS 87489 ROWS AND 8 COLUMNS

## COLUMN DETAILS
### It contains 9 columns
- **NAME**: Name of audiobook
- **AUTHOR**: Author of the audiobook
- **NARRATOR**: Narrator of the audiobook
- **TIME**: Length of the audiobook
- **RELEASEDATE**: Release date of the audiobook
- **LANGUAGE**: Language of the audiobook
- **STARS**: Number of stars the audiobook received
- **PRICE**: Price of the audiobook in INR
- **RATINGS**: Number of reviews received by the audiobook

# Issues Identified During Manual Inspection

## Dirty Data Issues

1. Column names are not standardized and need to be corrected.

2. The `Name` column contains:
   - Spelling mistakes
   - Character encoding issues (e.g., `â€™`, `Ã©`, `Ð`, `Ñ`)

3. Remove the prefix `WrittenBy:` from the `Written By` column.

4. Author names should be separated into:
   - First Name
   - Last Name

5. The `Written By` column contains encoding issues.

6. Remove the prefix `NarratedBy:` from the `Narrator` column.

7. The `Narrator` column contains encoding issues.

8. Narrator names should be separated into:
   - First Name
   - Last Name

9. The `Time` column should be converted to an appropriate datetime/time format.

10. Many records contain `Anonymous` as the author. Further investigation is required to determine whether this represents missing information or a legitimate author value.

11. The `Release Date` column should be converted to datetime format.
    - Mixed date formats are present:
      - `DD-MM-YYYY`
      - `MM-DD-YYYY`

12. The `Language` column contains inconsistent capitalization:
    - Uppercase values
    - Lowercase values
    - Title Case values

13. The `Price` column should be converted to a numeric data type after removing currency symbols.

14. The `Rating` column contains some empty values which are represented as 'Not rated yet"

---

## Untidy Data Issues

1. The `Ratings` column contains multiple variables in a single column:
   - Star Rating
   - Number of Reviews

   These should be separated into two independent columns:

   - `Stars`
   - `Number_of_Reviews`

In [11]:
audible_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         87489 non-null  str
 1   author       87489 non-null  str
 2   narrator     87489 non-null  str
 3   time         87489 non-null  str
 4   releasedate  87489 non-null  str
 5   language     87489 non-null  str
 6   stars        87489 non-null  str
 7   price        87489 non-null  str
dtypes: str(8)
memory usage: 5.3 MB

In [12]:
audible_dataset.sample(10)

,name,author,narrator,time,releasedate,language,stars,price
70226,Volare fino alle stelle,Writtenby:SusanElizabethPhillips,Narratedby:TittiSaraceno,12 hrs and 33 mins,18-08-18,italian,Not rated yet,766.00
57863,Rich Dad Poor Dad,Writtenby:RobertT.Kiyosaki,Narratedby:TimWheeler,6 hrs and 9 mins,15-06-12,English,"4.5 out of 5 stars5,324 ratings",837.00
70647,Christmas in Bayberry,"Writtenby:JenniferFaye,HallmarkPublishing",Narratedby:EmilyRankin,8 hrs and 46 mins,21-07-20,English,Not rated yet,820.00
54317,One Day in December,Writtenby:JosieSilver,"Narratedby:EleanorTomlinson,CharlieAnson",10 hrs and 27 mins,23-08-18,English,4 out of 5 stars48 ratings,820.00
66597,Hiding in the Pews,"Writtenby:SteveAustin,RobertW.Lee-foreword",Narratedby:AdamVerner,7 hrs and 8 mins,02-11-21,English,Not rated yet,586.00
33025,Sitting Together,"Writtenby:SusanM.PollakEdD,ThomasPedulla,Ronal...",Narratedby:PaulBrion,7 hrs and 44 mins,08-10-19,English,Not rated yet,586.00
25727,In Cold Blood,Writtenby:TrumanCapote,Narratedby:ScottBrick,14 hrs and 27 mins,03-01-06,English,4.5 out of 5 stars21 ratings,"1,131.00"
71279,Winter Wishes,"Writtenby:FernMichaels,SusanFox,JulesBennett,",Narratedby:AmyMcFadden,10 hrs and 51 mins,31-10-17,English,Not rated yet,"1,005.00"
71806,Opnieuw beginnen,Writtenby:RobinPilcher,Narratedby:GwennyVos,11 hrs and 41 mins,11-02-22,dutch,Not rated yet,267.00
81214,How Football Explains America,Writtenby:SalPaolantonio,Narratedby:PaulBoehmer,7 hrs and 10 mins,26-03-14,English,Not rated yet,668.00

In [13]:
audible_dataset.duplicated().sum()

np.int64(0)

In [14]:
audible_dataset.describe()

,name,author,narrator,time,releasedate,language,stars,price
count,87489,87489,87489,87489,87489,87489,87489,87489
unique,82767,48374,29717,2284,5058,36,665,1011
top,The Art of War,"Writtenby:矢島雅弘,石橋遊",Narratedby:anonymous,2 mins,16-05-18,English,Not rated yet,586.00
freq,20,874,1034,372,773,61884,72417,5533

In [15]:
audible_dataset.head()

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00

In [16]:
audible_dataset.tail()

,name,author,narrator,time,releasedate,language,stars,price
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,English,Not rated yet,596.00
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820.00
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680.00
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569.00